apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: eks-acg
  region: us-east-2
  version: "1.20"

vpc:
  cidr: 10.0.0.0/16

nodeGroups:
  - name: eks-node-group
    instanceType: t3.micro
    desiredCapacity: 3
    privateNetworking: true