Description: Hosted Zone and ACM Certificate
Parameters:
  DomainName:
    Description: The base Domain Name
    Type: String
  HostedZoneId:
    Description: The Hosted ID to validate the certificate
    Type: String
Resources:
  Certificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: !Sub "*.${DomainName}"
      SubjectAlternativeNames: !Ref DomainName
      DomainValidationOptions:
        - DomainName:
            Ref: DomainName
          HostedZoneId:
            Ref: HostedZoneId
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Name
          Value: !Ref DomainName
      ValidationMethod: DNS
