Description: Resource API IAM Policy
Parameters:
  Namespace:
    Description: The namespace which this table belongs to
    Type: String
    Default: development
Resources:
  IamPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Action:
            - dynamodb:BatchGetItem
            - dynamodb:PutItem
            - dynamodb:DescribeTable
            - dynamodb:DeleteItem
            - dynamodb:GetItem
            - dynamodb:Scan
            - dynamodb:Query
            - dynamodb:UpdateItem
          Resource:
            - Fn::Sub: arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${Namespace}-resources
            - Fn::Sub: arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${AWS::AccountId}/index/*
      ManagedPolicyName:
        Fn::Sub: "${Namespace}-ResourceApiPolicy"
Outputs:
  IamPolicyArn:
    Value:
      Ref: IamPolicy
