apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: eks-acg
  region: us-east-1
  version: "1.20"

vpc:
  cidr: 10.0.0.0/16

fargateProfiles:
  - name: acg-fargate-development
    selectors:
      - namespace: development
