Description: Clients API DynamoDB Table
Parameters:
  Namespace:
    Description: The namespace which this table belongs to
    Type: String
    Default: development
Resources:
  DynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
      - AttributeName: _id
        AttributeType: S
      KeySchema:
      - AttributeName: _id
        KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      TableName: !Sub "${Namespace}-clients"
