apiVersion: v1
kind: Secret
metadata:
  name: {{ template "acg-front-end.fullname" . }}-config-file
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  config.json: {{ tpl (.Files.Get "config.json.tpl") . | b64enc | quote }}