name: CI
run-name: It is a CI workflow for Frontend EKS/ECS Project 🚀
on:
  push:
    branches:
    - 'feature/**'
    # paths:
    # - 'front-end/**'
jobs:
  BuildAndTesting:
    runs-on: ubuntu-16.04
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20.x'
    - uses: actions/setup-python@v5
      with:
        python-version: '3.10' 
    - run: python --version
    - name: Cache node modules
      id: cache-npm
      uses: actions/cache@v3
      env:
        cache-name: cache-node-modules
      with:
      # npm cache files are stored in `~/.npm` on Linux/macOS
        path: ~/.npm
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-
    - name: Install Dependancies
      run: npm install
      working-directory: ./front-end
    - name: Building Application
      run: npm run build --if-present
      working-directory: ./front-end
    - name: Test The Application
      run: npm test
      working-directory: ./front-end